package com.reservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MunicipioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipioAllPropertiesEquals(Municipio expected, Municipio actual) {
        assertMunicipioAutoGeneratedPropertiesEquals(expected, actual);
        assertMunicipioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipioAllUpdatablePropertiesEquals(Municipio expected, Municipio actual) {
        assertMunicipioUpdatableFieldsEquals(expected, actual);
        assertMunicipioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipioAutoGeneratedPropertiesEquals(Municipio expected, Municipio actual) {
        assertThat(expected)
            .as("Verify Municipio auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipioUpdatableFieldsEquals(Municipio expected, Municipio actual) {
        assertThat(expected)
            .as("Verify Municipio relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipioUpdatableRelationshipsEquals(Municipio expected, Municipio actual) {
        assertThat(expected)
            .as("Verify Municipio relationships")
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()));
    }
}
