package com.reservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PessoaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAllPropertiesEquals(Pessoa expected, Pessoa actual) {
        assertPessoaAutoGeneratedPropertiesEquals(expected, actual);
        assertPessoaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAllUpdatablePropertiesEquals(Pessoa expected, Pessoa actual) {
        assertPessoaUpdatableFieldsEquals(expected, actual);
        assertPessoaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAutoGeneratedPropertiesEquals(Pessoa expected, Pessoa actual) {
        assertThat(expected)
            .as("Verify Pessoa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaUpdatableFieldsEquals(Pessoa expected, Pessoa actual) {
        assertThat(expected)
            .as("Verify Pessoa relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getSobrenome()).as("check sobrenome").isEqualTo(actual.getSobrenome()))
            .satisfies(e -> assertThat(e.getCpf()).as("check cpf").isEqualTo(actual.getCpf()))
            .satisfies(e -> assertThat(e.getDataNascimento()).as("check dataNascimento").isEqualTo(actual.getDataNascimento()))
            .satisfies(e -> assertThat(e.getTelefone()).as("check telefone").isEqualTo(actual.getTelefone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaUpdatableRelationshipsEquals(Pessoa expected, Pessoa actual) {}
}
