package com.reservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoQuartoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoQuartoAllPropertiesEquals(TipoQuarto expected, TipoQuarto actual) {
        assertTipoQuartoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoQuartoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoQuartoAllUpdatablePropertiesEquals(TipoQuarto expected, TipoQuarto actual) {
        assertTipoQuartoUpdatableFieldsEquals(expected, actual);
        assertTipoQuartoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoQuartoAutoGeneratedPropertiesEquals(TipoQuarto expected, TipoQuarto actual) {
        assertThat(expected)
            .as("Verify TipoQuarto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoQuartoUpdatableFieldsEquals(TipoQuarto expected, TipoQuarto actual) {
        assertThat(expected)
            .as("Verify TipoQuarto relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoQuartoUpdatableRelationshipsEquals(TipoQuarto expected, TipoQuarto actual) {}
}
